openapi: 3.0.0
info:
  title: Vite + Express API
  description: API for fetching MongoDB data
  version: 1.0.0

servers:
  - url: http://localhost:5000
    description: Local development server

paths:
  /items:
    get:
      summary: Retrieve all items from MongoDB
      responses:
        '200':
          description: Successfully fetched items
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                    name:
                      type: string